server:
  port: 8080


spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  datasource: #数据库设置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site?useUnicode=true&characterEncoding=utf-8
    username: root
    password: syxsyx
  profiles:
    active: dev


mybatis:
  type-aliases-package: com.syx.syxsite.model #对该包下的类自动启用别名
  config-location: classpath:mybatis/mybatis-config.xml #注册配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #对该包下的xml文件自动注册

#分页pageHelper
pagehelper:
  helper-dialect: mysql #配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  reasonable: true #配置分页参数合理化功能，默认是false。 #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页；
  #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  support-methods-arguments: true #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。

##配置日志类
logging:
  level:
    root: debug
